// This file contains all the data about each beach

const beaches = [
  {
    id: "0",
    beachName: "Running",
    beachStatus: "Low risk",
    latitude: "50.711087",
    longitude: "-1.895755",
    latitudeParking: "50.714850",
    longitudeParking: "-1.890675",
    lifeguarded: "No",
    publicToilets: "Yes",
    parkingAvailability: "No parking at this beach",
    dogWalking: "Yes",
    cycling: "Yes",
    bbq: "Only allowed after 6pm",
    warningInfo: "",
    imagePath: require("../assets/running.png"),
  },
  {
    id: "1",
    beachName: "Cycling",
    beachStatus: "Low risk",
    latitude: "50.731404",
    longitude: "-1.731441",
    latitudeParking: "50.728744",
    longitudeParking: "-1.734910",
    lifeguarded: "No",
    publicToilets: "Yes",
    parkingAvailability: "67",
    dogWalking: "Yes",
    cycling: "Yes",
    bbq: "Only allowed after 6pm",
    warningInfo: "",
  },
  {
    id: "2",
    beachName: "Boscombe Beach East",
    latitude: "50.719996",
    longitude: "-1.841179",
    latitudeParking: "50.720522",
    longitudeParking: "-1.842338",
    beachStatus: "Moderate-high",
    lifeguarded: "No",
    publicToilets: "Yes",
    parkingAvailability: "No parking at this beach",
    dogWalking: "No",
    cycling: "No",
    bbq: "Only allowed after 6pm",
    warningInfo: "",
  },
  {
    id: "3",
    beachName: "Boscombe Beach West",
    latitude: "50.719702",
    longitude: "-1.845608",
    latitudeParking: "50.720522",
    longitudeParking: "-1.842338",
    beachStatus: "Moderate-high",
    lifeguarded: "No",
    publicToilets: "Yes",
    parkingAvailability: "43",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Permitted in the designated area only",
  },
  {
    id: "4",
    beachName: "Bournemouth Beach East",
    latitude: "50.716826",
    longitude: "-1.870989",
    latitudeParking: "50.717070",
    longitudeParking: "-1.873347",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "23",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Permitted in the designated area only",
  },
  {
    id: "5",
    beachName: "Bournemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "7",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "8",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "9",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "10",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "11",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
  {
    id: "12",
    beachName: "Bossssssurnemouth Beach West",
    latitude: "50.715330",
    longitude: "-1.878462",
    latitudeParking: "50.717687",
    longitudeParking: "-1.881558",
    beachStatus: "Moderate-high",
    lifeguarded: "Yes",
    publicToilets: "Yes",
    parkingAvailability: "26",
    dogWalking: "No",
    cycling: "No",
    warningInfo: "",
    bbq: "Only allowed after 6pm",
  },
];

const getBeaches = () => {
  return beaches;
};

export default getBeaches;
